# docker-compose.yml
services:
  db:
    image: postgres:17         # “17” will always pull the latest 17.x patch release
    container_name: finance-db
    environment:
      POSTGRES_DB: finance_app
      POSTGRES_USER: finance_user
      POSTGRES_PASSWORD: securepassword
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U finance_user"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
